version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/src/ingester/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/client/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "tests/" 
    schedule:
      interval: "weekly"
