version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.1.5
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${DOKU_DB_PASSWORD:-DOKU}   
      CLICKHOUSE_USER: ${DOKU_DB_USER:-default}                   
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "${DOKU_DB_PORT:-9000}:9000" 
    restart: always

  doku-ingester:
    image: ghcr.io/patcher99/doku-ingester:0.0.8
    container_name: doku-ingester
    environment:
      DOKU_DB_HOST: clickhouse   
      DOKU_DB_PORT: ${DOKU_DB_PORT:-9000} 
      DOKU_DB_NAME: ${DOKU_DB_NAME:-default}     
      DOKU_DB_USER: ${DOKU_DB_USER:-default}              
      DOKU_DB_PASSWORD: ${DOKU_DB_PASSWORD:-DOKU}
    ports:
      - "9044:9044"         
    depends_on:
      - clickhouse
    restart: always

volumes:
  clickhouse-data: