apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: default
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server
        ports:
        - containerPort: 9000
        - containerPort: 8123
        env:
        - name: CLICKHOUSE_PASSWORD
          value: DOKU
        - name: CLICKHOUSE_USER
          value: default
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-storage
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: default
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: clickhouse
  - port: 8123
    targetPort: 8123
    name: http
  type: LoadBalancer
  selector:
    app: clickhouse