apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doku.fullname" . }}-db-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.config.db_user }}
  DB_PASSWORD: {{ .Values.config.db_password }}
  DB_NAME: {{ .Values.config.db_name }}
  DB_HOST: {{ .Values.config.db_host }}.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "{{ .Values.config.db_port }}"
  DB_SSLMODE: {{ .Values.config.db_sslmode }}
  DATA_TABLE_NAME: {{ .Values.config.data_table_name }}
  APIKEY_TABLE_NAME: {{ .Values.config.apikey_table_name }}
  DB_MAX_OPEN_CONNS: "{{ .Values.config.db_max_open_conns }}"
  DB_MAX_IDLE_CONNS: "{{ .Values.config.db_max_idle_conns }}"