openapi: 3.0.0
info:
  title: API Keys Service
  description: This service manages API keys through GET, POST, and DELETE operations.
  version: "0.0.2"

servers:
  - url: https://127.0.0.1:9044/

paths:
  /api/keys:
    get:
      summary: Get a list of API keys
      operationId: getApiKeys
      tags:
        - API Key
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIKeyRequest'
      responses:
        '200':
          description: A list of API keys
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jsonResponse'
              
    post:
      summary: Create a new API key
      operationId: createApiKey
      tags:
        - API Key
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIKeyRequest'
      responses:
        '201':
          description: API key created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jsonResponse'
                
    delete:
      summary: Delete an API key
      operationId: deleteApiKey
      tags:
        - API Key
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIKeyRequest'
      responses:
        '200':
          description: API key deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jsonResponse'

components:
  schemas:
    APIKeyRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    jsonResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string
          
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization