receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  basicauth/tempo:
    client_auth:
      username: "878543"
      password: "glc_eyJvIjoiNjUyOTkyIiwibiI6InN0YWNrLTkyNjQ0Ni1pbnRlZ3JhdGlvbi1hZGFzIiwiayI6IjFvNHFUTjM3a3RxTGswMkgwOG1aNjJJTyIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19"
  basicauth/prometheus:
    client_auth:
      username: "1568361"
      password: "glc_eyJvIjoiNjUyOTkyIiwibiI6InN0YWNrLTkyNjQ0Ni1pbnRlZ3JhdGlvbi1hZGFzIiwiayI6IjFvNHFUTjM3a3RxTGswMkgwOG1aNjJJTyIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19"
exporters:
  prometheusremotewrite:
    endpoint: "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"
    add_metric_suffixes: false
    auth:
      authenticator: basicauth/prometheus
  otlp:
    endpoint: "tempo-prod-04-prod-us-east-0.grafana.net:443"
    auth:
      authenticator: basicauth/tempo
service:
  extensions: [ basicauth/tempo, basicauth/prometheus ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ prometheusremotewrite ]
