receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  zpages: {}
exporters:
  clickhouse:
    endpoint: tcp://146.190.11.107:9000?dial_timeout=10s
    database: openlit
    username: default
    password: DOKU
    ttl: 72h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
    traces:
      receivers: [ otlp ]
      processors: [memory_limiter, batch]
      exporters: [ clickhouse ]
    metrics:
      receivers: [ otlp ]
      processors: [memory_limiter, batch]
      exporters: [ clickhouse ]
